# Generated by Django 2.2.20 on 2021-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210423_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('account', models.CharField(max_length=32)),
                ('ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=5000)),
                ('lastLogDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
